# Generated by Django 4.0.2 on 2022-12-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='id',
        ),
        migrations.AddField(
            model_name='skillsection',
            name='base_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolioApi.base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='base_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolioApi.base'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutmesection',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Icon (eg: fa -fa-twitter)'),
        ),
        migrations.AlterField(
            model_name='jumbo',
            name='jumbo_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='languageicons',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicesoffred',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicesoffred',
            name='shadow_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillsection',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Icon (eg: bi-envelope)'),
        ),
    ]
